### ISSUE TITLE
Elastix is not found on MacOSX

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerElastix#2]
Currently Elastix is not bundled correctly in the extension.

Workaround that users can apply until the issue is fixed:
* Download Elastix from: http://elastix.isi.uu.nl/download.php
* Install Elastix as described in the user guide or here: https://superuser.com/questions/884179/how-to-install-elastix-a-toolbox-for-rigid-and-nonrigid-registration-of-images)
* In Slicer, in `General Registration (Elastix)` module, open `Advanced` section, set `Custom Elastix toolbox location` to point to the directory where you installed Elastix

**Comment by jcfr** [comment]
Fixed in https://github.com/lassoan/SlicerElastix/commit/01d6b26d30417071a77e596147933e2f6adb0a03
