### ISSUE TITLE
Running Elastix registration changes save location of "fixed" and "moving" volumes

### ISSUE THREAD

**Issue by hbraunDSP** [lassoan/SlicerElastix#23]
After running Elastix the volumes I selected for the “fixed” and “moving” volumes are by default saved as metaImage (*.mha) files in the [home]/AppData/Local/Temp/Slicer/Elastix/[datetime]/input/ directory. This behavior is unexpected and annoying: The original volumes are unchanged and they should remain unaltered in their original location.

**Comment by lassoan** [comment]
Thank you for reporting this. The issue is now fixed. You can update SlicerElastix extension tomorrow or later to get this fix.
