### ISSUE TITLE
Elastix won't run on unsaved scene

### ISSUE THREAD

**Issue by hbraunDSP** [lassoan/SlicerElastix#24]
I had the following error when trying to run SlicerElastix revision ba52785, Slicer version 4.10.0, Windows 10: 

```
ERROR: could not read fixed image.

itk::ImageFileReaderException (0000006C06FDEBE8)
Location: "unknown"
File: d:\d\s\slicer-4100-build\itk\modules\io\imagebase\include\itkImageFileReader.hxx
Line: 143
Description: Could not create IO object for reading file C:/Users/hbraun/AppData/Local/Temp/Slicer/Elastix/20190913_155457_404\input\fixed.mha
The file doesn't exist.
Filename = C:/Users/hbraun/AppData/Local/Temp/Slicer/Elastix/20190913_155457_404\input\fixed.mha
```
I had just added the images to the scene and had not saved yet. Saving the scene as MRB did not fix the problem, but restarting Slicer and reloading the MRB did.  At first glance it looks like this is probably an issue with POSIX vs Windows file separators ('\\' vs '/') since I see both mixed together in the error text.

**Comment by lassoan** [comment]
Does it work if you use an official release - latest stable (4.10.2) or a recent preview?

If you enable "Keep temporary files" in Advanced section, does the file that ITK complains about exist?

**Comment by hbraunDSP** [comment]
It seems to be working with Slicer 4.10.2. I'm closing this.
