### ISSUE TITLE
vtkMatrixFromArray not found

### ISSUE THREAD

**Issue by felixvh** [lassoan/SlicerElastix#26]
I'm working with the Elastix toolbox for Slicer and I was trying to get the transforms that you receive from the toolbox. Anyways, I found that the above mentioned function is not supported anymore by slicer.util. I found a work around by using DeepCopy. Was vtkMatrixFromArray removed in a newer version?

https://github.com/lassoan/SlicerElastix/blob/74a4cfc61169cd398e9d03880c0e0ca1a3b51eb2/Elastix/Elastix.py#L611

**Comment by lassoan** [comment]
slicer.util.vtkMatrixFromArray is only available in recent Slicer-4.11 versions. To make SlicerElastix work with Slicer-4.10 as well, a copy of the method is added locally. See here: https://github.com/lassoan/SlicerElastix/blob/74a4cfc61169cd398e9d03880c0e0ca1a3b51eb2/Elastix/Elastix.py#L942-L945

If you encountered a problem related to this then please reopen and describe what Slicer version you used.
