### ISSUE TITLE
Is generic rigid preset actually rigid? 

### ISSUE THREAD

**Issue by zapaishchykova** [lassoan/SlicerElastix#35]
Hello Andras!
First of all, thanks for the great work! 
I have a question regarding the elastix generic rigid preset - it looks to me that both in slicer3d and in python when I use this [preset](https://github.com/lassoan/SlicerElastix/blob/master/Elastix/Resources/RegistrationParameters/Parameters_Rigid.txt) the output volume has 1x1x1mm spacing. Does that mean that this registration is not rigid then? 

Thanks!

**Comment by lassoan** [comment]
The rigid preset performs rigid registration.

You can disable "Force grid output transform" in Advanced section to save the result in a simple linear transformation matrix. You can then harden the transform on the moving image without resampling it.

**Comment by zapaishchykova** [comment]
brilliant, got it, thanks!
