### ISSUE TITLE
Elastix not found on Mac

### ISSUE THREAD

**Issue by pieper** [lassoan/SlicerElastix#4]
Installed SlicerElastix extension but it failed to find elastix.

Setting the path manually to this works:

/Applications/Slicer-4.8.0.app/Contents/Extensions-26489/SlicerElastix/lib/Slicer-4.8

looks like a simple script change fixes this - I'll make a PR

**Comment by pieper** [comment]
Wait - looks like this was already fixed on master but not 4.8.  Would be good to bump the 4.8 hash.

**Comment by jcfr** [comment]
> Would be good to bump the 4.8 hash.

👍 

The easiest would be cherry pick all commit from 4.9 back onto the 4.8 release branch.

**Comment by lassoan** [comment]
Ok, I'll do that today.

**Comment by jcfr** [comment]
Since I add already a source tree ready based on [these instructions](https://www.slicer.org/wiki/Documentation/Nightly/Developers/ReleaseProcess#Release).

I run the following command:

```
cd Slicer-4.8
git fetch origin
git cherry-pick 37ac135
git cherry-pick 06dd46d..2982333
git svn dcommit --add-author-from
git push origin git push origin master-48
```

The branch on SVN and on Github have all commit from 4.9 backported except the one labelled `ENH: Begin 4.9.0 development`

http://viewvc.slicer.org/viewvc.cgi/Slicer4/branches/Slicer-4-8/
https://github.com/Slicer/Slicer/commits/master-48

**Comment by jcfr** [comment]
Next steps are:
* update the version to 4.8.1 in the release branch
* update the release scripts (Slicer/DashboardScripts repo)
* trigger release
* sign windows package
* etc ... see checklist

Whenever you think we are ready, we can release ...

**Comment by lassoan** [comment]
Is this still an issue? Does SlicerElastix works on Mac using 4.8 and nightly Slicer?

**Comment by jcfr** [comment]
It is on my list before cutting 4.8.1.

**Comment by lassoan** [comment]
Is this still an issue? Does SlicerElastix works on Mac using 4.10 and nightly Slicer?

**Comment by lassoan** [comment]
This should fix the Mac build: https://github.com/lassoan/SlicerElastix/commit/bfe0d9786e138a3a46df5b4022281cd49d844043

**Comment by lassoan** [comment]
Also [had to update Elastix to latest version](https://github.com/lassoan/SlicerElastix/commit/ba52785d5c9cca1d2d5f78633eeadfdae9908546). It should work in tomorrow's nightly build.

**Comment by lassoan** [comment]
This should work correctly now.
