### ISSUE TITLE
Slicer extension macOS packaging is failing

### ISSUE THREAD

**Issue by jcfr** [lassoan/SlicerElastix#43]
Before the fixup process is initiated, we can observe that the following executable already reference library using `@rpath`.

To allow the extension process to successfully complete, absolute path are expected:

### elastix

```
otool -L elastix 
elastix:
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/path/to/ITK-build/lib/libITKConvolution-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/path/to/ITK-build/lib/libITKLabelMap-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	[...]
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
	/path/to/ITK-build/lib/libitkdouble-conversion-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libunwind.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

### transformix

```
otool -L transformix
transformix:
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/path/to/ITK-build/lib/libITKConvolution-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/path/to/ITK-build/lib/libITKLabelMap-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	[...]
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
	/path/to/ITK-build/lib/libitkdouble-conversion-5.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libunwind.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

To disable the fixup, the following patch was locally applied to the associated Slice source tree:

```diff
git diff 
diff --git a/CMake/SlicerExtensionCPack.cmake b/CMake/SlicerExtensionCPack.cmake
index 6adec7bcac..b81e02f701 100644
--- a/CMake/SlicerExtensionCPack.cmake
+++ b/CMake/SlicerExtensionCPack.cmake
@@ -275,7 +275,7 @@ install(SCRIPT \"${slicer_extension_cpack_bundle_fixup_directory}/SlicerExtensio
     if(NOT result EQUAL 0)
       message(FATAL_ERROR "${EXTENSION_NAME}-Fixup: Failed to configure project [source_dir:${source_dir}, build_dir:${build_dir}")
     endif()
-    set(CPACK_INSTALL_CMAKE_PROJECTS "${CPACK_INSTALL_CMAKE_PROJECTS};${build_dir};${EXTENSION_NAME}-Fixup;ALL;/")
+    #set(CPACK_INSTALL_CMAKE_PROJECTS "${CPACK_INSTALL_CMAKE_PROJECTS};${build_dir};${EXTENSION_NAME}-Fixup;ALL;/")
   endif()
 endif()
```

Once the packaging has been generated with the fixup disabled using `make package`, the fixup can then explicitly be initiated using:

```
cd /path/to/S-0-E-b/SlicerElastix-build/inner-build

cp -r _CPack_Packages _CPack_Packages.orig

cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=/path/to/S-0-E-b/SlicerElastix-build/inner-build/_CPack_Packages/Darwin/TGZ/32195-macosx-amd64-SlicerElastix-gitd98ebde-2023-08-03/ \
  -P ./SlicerExtensionBundle/SlicerExtensionCPackBundleFixup.cmake
```

Doing so allow to more easily debug and identify issues.

Copying `_CPack_Packages` to `_CPack_Packages.orig` may allow to restore the "packaged" tree before attempting to re-run the script. Helpful if it was updated and to avoid re-running `make package`

**Comment by jcfr** [comment]
The "problematic" libraries being linked into `elastix` and `transformix` are specific to OpenMP  (linker flag `-fopenmp=libomp` added after looking up `OpenMP` dependency[^1])

[^1]: https://github.com/SuperElastix/elastix/blob/5.1.0/CMakeLists.txt#L118-L132

On the macOS build machine (`computron`) used to build the official Slicer extension, we are not using the compiler provided by default by XCode, instead we are using `clang 14.0.6`[^2] downloaded from the `llvm` project.

[^2]: https://discourse.slicer.org/t/transition-of-macos-preview-build-from-host-10-13-high-sierra-to-13-ventura/28668/3?u=jcfr

The libraries are made available through the compiler we installed:

```
% pwd
/path/to/Support/clang+llvm-14.0.6-x86_64-apple-darwin 

% find . | grep -E "libomp.dylib|unwind.dylib|libc\+\+.dylib"
./lib/libomp.dylib
./lib/libunwind.dylib
./lib/libc++.dylib

% otool -L ./lib/libomp.dylib
./lib/libomp.dylib:
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

% otool -L ./lib/libunwind.dylib 
./lib/libunwind.dylib:
	@rpath/libunwind.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

% otool -L ./lib/libc++.dylib 
./lib/libc++.dylib:
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	@rpath/libc++abi.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by jcfr** [comment]
After talking with @thewtex, the use of OpenMP should not be critical and could be disabled.

Alternatively, we could switch to using [itk-elastix](https://pypi.org/project/itk-elastix/) Python package.

**Comment by lassoan** [comment]
THanks for the investigation @jcfr.

I'm not sure if we can remove OpenMP support, as it is used in other extensions, too. For example, SlicerRT extension's Plastimatch library heavily depends on it.

**Comment by lassoan** [comment]
OpenMP in SlicerElastix build of Elastix is disabled now - https://github.com/lassoan/SlicerElastix/issues/44#issuecomment-1989207504
