### ISSUE TITLE
error when run make package

### ISSUE THREAD

**Issue by idhamari** [lassoan/SlicerElastix#6]
System: Ubuntu 16

CPack Error: Not enough items on list: CPACK_INSTALL_CMAKE_PROJECTS. CPACK_INSTALL_CMAKE_PROJECTS should hold quadruplet of install directory, install project name, install component, and install subdirectory.
CPack Error: Error when generating package: SlicerElastix
Makefile:83: recipe for target 'package' failed

**Comment by lassoan** [comment]
I can work on this when Slicer nightly builds are updated for linux to use cxx11 compiler. It should happen any day now.
